server:
  port: 9494

spring:
  application:
    name: GATEWAY-SERVICE

  cloud:
    gateway:
      routes:
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/v1/orders/**
          filters:
            - name: AuthenticationFilter
            - name: CircuitBreaker
              args:
                name: callOrderFallback
                fallbackUri: forward:/fallback/order-service
        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/api/v1/payment/**
          filters:
            - name: AuthenticationFilter
            - name: CircuitBreaker
              args:
                name: callPaymentFallback
                fallbackUri: forward:/fallback/payment-service
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/user/**
          filters:
            - name: AuthenticationFilter
            - name: CircuitBreaker
              args:
                name: callUserFallback
                fallbackUri: forward:/fallback/user-service
        - id: security-service
          uri: lb://SECURITY-SERVICE
          predicates:
            - Path=/security/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
